// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFouIx_tb712OMl_i99H24F4A9n6PscHI',
    appId: '1:80823516377:web:189fcfeee05cdb46e792c8',
    messagingSenderId: '80823516377',
    projectId: 'projectxd-e9238',
    authDomain: 'projectxd-e9238.firebaseapp.com',
    storageBucket: 'projectxd-e9238.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaOfJ0xfuyzfkLOpcIAcB2pajEn6oM6pM',
    appId: '1:80823516377:android:2d641a655a051cd3e792c8',
    messagingSenderId: '80823516377',
    projectId: 'projectxd-e9238',
    storageBucket: 'projectxd-e9238.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4MojKy5eQbpujT_hJ0tLdX7Z3M0wz4k8',
    appId: '1:80823516377:ios:ce6ee97283505ed3e792c8',
    messagingSenderId: '80823516377',
    projectId: 'projectxd-e9238',
    storageBucket: 'projectxd-e9238.firebasestorage.app',
    iosBundleId: 'com.example.projectV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4MojKy5eQbpujT_hJ0tLdX7Z3M0wz4k8',
    appId: '1:80823516377:ios:ce6ee97283505ed3e792c8',
    messagingSenderId: '80823516377',
    projectId: 'projectxd-e9238',
    storageBucket: 'projectxd-e9238.firebasestorage.app',
    iosBundleId: 'com.example.projectV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFouIx_tb712OMl_i99H24F4A9n6PscHI',
    appId: '1:80823516377:web:5fb0b7fbc86ecbdce792c8',
    messagingSenderId: '80823516377',
    projectId: 'projectxd-e9238',
    authDomain: 'projectxd-e9238.firebaseapp.com',
    storageBucket: 'projectxd-e9238.firebasestorage.app',
  );
}
